/* Arrow Out — framework-free game logic.
   Shared by ArrowsGame.vue and the Vitest test suite.

   Rule: every piece is a rigid snake of cells with a designated exit direction
   (the "head" direction). Tap a piece and it slides off the board in that
   direction — but ONLY if every cell of the piece has a clear ray all the way
   to the edge (no other piece in the way). Pieces are generated by reverse-
   placement, which guarantees every puzzle is solvable. */

import type { Rng } from "~/utils/rng";

// ------------------------------------------------------------------ types

export interface Cell {
  r: number;
  c: number;
}

export type Dir = "up" | "down" | "left" | "right";

export interface PieceData {
  cells: Cell[]; // tail → head order
  dir: Dir;
}

export interface DiffConfig {
  key: string;
  label: string;
  n: number;
  fill: number;
  lens: number[];
  bend: number;
}

// ------------------------------------------------------------------ constants

export const DIRV: Record<Dir, [number, number]> = {
  up: [-1, 0],
  down: [1, 0],
  left: [0, -1],
  right: [0, 1],
};

export const DIRS: Dir[] = ["up", "down", "left", "right"];

export const OPP: Record<Dir, Dir> = {
  up: "down",
  down: "up",
  left: "right",
  right: "left",
};

export const DIFFS: DiffConfig[] = [
  { key: "easy",   label: "簡單", n: 5, fill: 14, lens: [1, 1, 1, 1, 2, 2, 2, 3],    bend: 0.22 },
  { key: "medium", label: "中等", n: 6, fill: 22, lens: [1, 1, 2, 2, 2, 3, 3, 4],    bend: 0.45 },
  { key: "hard",   label: "困難", n: 7, fill: 33, lens: [2, 2, 3, 3, 3, 4, 4, 5],    bend: 0.62 },
];

// ------------------------------------------------------------------ geometry

/** True if (r, c) is inside an N×N board. */
export function inBounds(r: number, c: number, N: number): boolean {
  return r >= 0 && r < N && c >= 0 && c < N;
}

/** True if every cell's forward ray (in `dir`) is free of other-piece cells
 *  all the way to the board edge. `occ` maps (r*N+c) → true for occupied cells
 *  that belong to OTHER pieces (the sweeping piece's own cells must be excluded). */
export function sweepClear(cells: Cell[], dir: Dir, occ: Set<number>, N: number): boolean {
  const [dr, dc] = DIRV[dir];
  for (const { r, c } of cells) {
    let rr = r + dr, cc = c + dc;
    while (inBounds(rr, cc, N)) {
      if (occ.has(rr * N + cc)) return false;
      rr += dr; cc += dc;
    }
  }
  return true;
}

// ------------------------------------------------------------------ generation helpers

/** Grow a snake path starting from `startIdx`, up to `targetLen` cells.
 *  Returns an array of cell indices (not Cell objects). */
export function growSnake(
  rng: Rng,
  occ: Set<number>,
  startIdx: number,
  N: number,
  targetLen: number,
  bend: number,
): number[] {
  const path = [startIdx];
  const inPath = new Set([startIdx]);
  let prevDir: Dir | null = null;
  while (path.length < targetLen) {
    const last = path[path.length - 1];
    const r = (last / N) | 0, c = last % N;
    const opts: { d: Dir; ni: number }[] = [];
    for (const d of DIRS) {
      const nr = r + DIRV[d][0], nc = c + DIRV[d][1];
      if (!inBounds(nr, nc, N)) continue;
      const ni = nr * N + nc;
      if (occ.has(ni) || inPath.has(ni)) continue;
      opts.push({ d, ni });
    }
    if (!opts.length) break;
    const turns = prevDir
      ? opts.filter((o) => o.d !== prevDir && o.d !== OPP[prevDir!])
      : opts;
    const straight = prevDir ? opts.filter((o) => o.d === prevDir) : [];
    let choice: { d: Dir; ni: number };
    if (prevDir && turns.length && rng.bool(bend)) choice = rng.pick(turns);
    else if (straight.length) choice = rng.pick(straight);
    else choice = rng.pick(opts);
    path.push(choice.ni);
    inPath.add(choice.ni);
    prevDir = choice.d;
  }
  return path;
}

/** Direction of travel from cell at index `aIdx` to adjacent cell at `bIdx`. */
export function segDir(aIdx: number, bIdx: number, N: number): Dir {
  const ar = (aIdx / N) | 0, ac = aIdx % N, br = (bIdx / N) | 0, bc = bIdx % N;
  if (br < ar) return "up";
  if (br > ar) return "down";
  if (bc < ac) return "left";
  return "right";
}

/** Convert flat cell indices to {r,c} objects. */
export function cellsOf(pathIdx: number[], N: number): Cell[] {
  return pathIdx.map((i) => ({ r: (i / N) | 0, c: i % N }));
}

/** True when the last cell in `cells` (the head) is the furthest cell along
 *  `dir` — i.e. the chevron sits at the true leading tip. */
export function headFurthest(cells: Cell[], dir: Dir): boolean {
  const [dr, dc] = DIRV[dir];
  const proj = (cl: Cell) => cl.r * dr + cl.c * dc;
  const h = proj(cells[cells.length - 1]);
  for (const cl of cells) if (proj(cl) > h) return false;
  return true;
}

/** Try both endpoints of `pathIdx` as the head; return `{ cells, dir }` for the
 *  first candidate that is currently free to slide out, or null if neither works. */
export function chooseExit(
  rng: Rng,
  pathIdx: number[],
  occ: Set<number>,
  N: number,
): PieceData | null {
  const cands: { order: number[]; dir: Dir }[] = [];
  if (pathIdx.length === 1) {
    for (const d of DIRS) cands.push({ order: pathIdx.slice(), dir: d });
  } else {
    const last = pathIdx.slice();
    cands.push({ order: last, dir: segDir(last[last.length - 2], last[last.length - 1], N) });
    const first = pathIdx.slice().reverse();
    cands.push({ order: first, dir: segDir(first[first.length - 2], first[first.length - 1], N) });
  }
  rng.shuffle(cands);
  for (const cand of cands) {
    const cells = cellsOf(cand.order, N);
    if (!headFurthest(cells, cand.dir)) continue;
    if (sweepClear(cells, cand.dir, occ, N)) return { cells, dir: cand.dir };
  }
  return null;
}

// ------------------------------------------------------------------ level generation

/** Build one puzzle using reverse-placement: pieces are placed in reverse removal
 *  order so that removing them in any order always succeeds. */
export function buildOne(rng: Rng, cfg: DiffConfig): PieceData[] {
  const N = cfg.n;
  const occ = new Set<number>();
  const dead = new Set<number>();
  const built: PieceData[] = [];
  let guard = 0;
  const maxGuard = cfg.fill * 60;
  while (occ.size < cfg.fill && guard < maxGuard) {
    guard++;
    const empties: number[] = [];
    for (let i = 0; i < N * N; i++) if (!occ.has(i) && !dead.has(i)) empties.push(i);
    if (!empties.length) break;
    const start = rng.pick(empties);
    let placed: PieceData | null = null;
    const wantLen = rng.pick(cfg.lens);
    for (let t = 0; t < 3 && !placed; t++) {
      const target = Math.max(1, wantLen - t);
      const path = growSnake(rng, occ, start, N, target, cfg.bend);
      placed = chooseExit(rng, path, occ, N);
    }
    if (!placed) placed = chooseExit(rng, [start], occ, N); // last resort: single cell
    if (!placed) { dead.add(start); continue; }             // cell can never leave → skip
    for (const cl of placed.cells) occ.add(cl.r * N + cl.c);
    built.push({ cells: placed.cells, dir: placed.dir });
  }
  return built;
}

/** Compute how many "remove all currently-free pieces" rounds it takes to solve
 *  the puzzle. Returns -1 if unsolvable (should never happen for reverse-placed
 *  boards, but callers can reject such a result as a safety net). */
export function solveDepth(built: PieceData[], N: number): number {
  let remain = built.map((p) => ({ cells: p.cells, dir: p.dir }));
  let rounds = 0;
  while (remain.length) {
    const occ = new Map<number, number>();
    remain.forEach((p, i) => {
      for (const cl of p.cells) occ.set(cl.r * N + cl.c, i);
    });
    const freeIdx = new Set<number>();
    remain.forEach((p, i) => {
      const [dr, dc] = DIRV[p.dir];
      let ok = true;
      for (const cl of p.cells) {
        let r = cl.r + dr, c = cl.c + dc;
        while (inBounds(r, c, N)) {
          const o = occ.get(r * N + c);
          if (o !== undefined && o !== i) { ok = false; break; }
          r += dr; c += dc;
        }
        if (!ok) break;
      }
      if (ok) freeIdx.add(i);
    });
    if (!freeIdx.size) return -1;
    remain = remain.filter((_, i) => !freeIdx.has(i));
    rounds++;
  }
  return rounds;
}

// ------------------------------------------------------------------ gameplay logic

/** True if piece `p` can be removed right now: no other non-leaving piece blocks
 *  its forward ray in every cell.
 *  `activePieces` must contain only non-leaving pieces (the caller filters). */
export function isRemovable(p: PieceData & { id: number }, activePieces: Array<PieceData & { id: number }>, N: number): boolean {
  const occ = new Map<number, number>();
  for (const q of activePieces) {
    for (const cl of q.cells) occ.set(cl.r * N + cl.c, q.id);
  }
  const [dr, dc] = DIRV[p.dir];
  for (const cl of p.cells) {
    let r = cl.r + dr, c = cl.c + dc;
    while (inBounds(r, c, N)) {
      const o = occ.get(r * N + c);
      if (o !== undefined && o !== p.id) return false;
      r += dr; c += dc;
    }
  }
  return true;
}

/** True when all pieces have been cleared (the win condition). */
export function isWon(pieces: unknown[]): boolean {
  return pieces.length === 0;
}
