/* Maze 2-D — framework-free game logic extracted from Maze2dGame.vue.
   Shared by the Vue component and the unit tests.

   The maze is a perfect maze (spanning tree) generated by a recursive-backtracker
   DFS (iterative stack). Every pair of cells has exactly one path between them, so
   the maze is always solvable and there are no loops.

   Wall model
   ----------
   walls[row][col] is a Uint8 bitmask of *open passages* (NOT walls):
     N = 1  (row - 1)
     E = 2  (col + 1)
     S = 4  (row + 1)
     W = 8  (col - 1)
   A bit being SET means you can walk in that direction; UNSET means a wall blocks.
*/

import type { Rng } from "~/utils/rng";

// Direction bitmasks
export const DIR_N = 1;
export const DIR_E = 2;
export const DIR_S = 4;
export const DIR_W = 8;

/** For a given direction bit, the opposite direction bit. */
export const OPPOSITE: Record<number, number> = {
  [DIR_N]: DIR_S,
  [DIR_S]: DIR_N,
  [DIR_E]: DIR_W,
  [DIR_W]: DIR_E,
};

/** Row delta for each direction. */
export const DR: Record<number, number> = {
  [DIR_N]: -1,
  [DIR_S]: 1,
  [DIR_E]: 0,
  [DIR_W]: 0,
};

/** Col delta for each direction. */
export const DC: Record<number, number> = {
  [DIR_N]: 0,
  [DIR_S]: 0,
  [DIR_E]: 1,
  [DIR_W]: -1,
};

/**
 * The wall model: a 2-D array of Uint8Array rows.
 * walls[row][col] is a bitmask of open passages (see DIR_* constants).
 */
export type MazeWalls = Uint8Array[];

/**
 * Generate a perfect (spanning-tree) maze of `size × size` cells using a
 * seeded RNG.  Start cell is always [0, 0].
 *
 * Passing the same seed always yields the same maze (deterministic); passing
 * a different seed yields a different maze (varied).
 */
export function generateMaze(size: number, rng: Rng): MazeWalls {
  const r = size;
  const c = size;
  const walls: MazeWalls = Array.from({ length: r }, () => new Uint8Array(c));
  const cellVisited = Array.from({ length: r }, () => new Uint8Array(c));
  const stack: [number, number][] = [];

  cellVisited[0][0] = 1;
  stack.push([0, 0]);

  while (stack.length) {
    const [cr, cc] = stack[stack.length - 1];
    const dirs = rng.shuffle([DIR_N, DIR_E, DIR_S, DIR_W]);
    let moved = false;
    for (const d of dirs) {
      const nr = cr + DR[d];
      const nc = cc + DC[d];
      if (nr < 0 || nc < 0 || nr >= r || nc >= c) continue;
      if (cellVisited[nr][nc]) continue;
      // carve passage in both cells
      walls[cr][cc] |= d;
      walls[nr][nc] |= OPPOSITE[d];
      cellVisited[nr][nc] = 1;
      stack.push([nr, nc]);
      moved = true;
      break;
    }
    if (!moved) stack.pop();
  }
  return walls;
}

/**
 * Convert a (dr, dc) movement delta into the corresponding direction bitmask.
 * Returns 0 for invalid/diagonal deltas.
 */
export function deltaToDir(dr: number, dc: number): number {
  if (dr === -1 && dc === 0) return DIR_N;
  if (dr === 1 && dc === 0) return DIR_S;
  if (dr === 0 && dc === 1) return DIR_E;
  if (dr === 0 && dc === -1) return DIR_W;
  return 0;
}

/**
 * Return true when the player at (row, col) may step in direction (dr, dc).
 * A move is legal when:
 *   1. The direction is one of the four cardinal directions.
 *   2. The corresponding passage bit is set in the walls model (no wall).
 *   3. The destination cell is within the grid bounds.
 */
export function canMove(
  walls: MazeWalls,
  rows: number,
  cols: number,
  row: number,
  col: number,
  dr: number,
  dc: number,
): boolean {
  const dir = deltaToDir(dr, dc);
  if (!dir) return false;
  if (!(walls[row][col] & dir)) return false; // wall blocks
  const nr = row + dr;
  const nc = col + dc;
  return nr >= 0 && nc >= 0 && nr < rows && nc < cols;
}

/**
 * Return true when the player has reached the exit cell (bottom-right corner).
 */
export function isAtExit(row: number, col: number, rows: number, cols: number): boolean {
  return row === rows - 1 && col === cols - 1;
}

/**
 * BFS from (0, 0) — return true when a path exists to (rows-1, cols-1).
 * Used to verify solvability of generated mazes.
 */
export function isSolvable(walls: MazeWalls, rows: number, cols: number): boolean {
  const seen = Array.from({ length: rows }, () => new Uint8Array(cols));
  const queue: [number, number][] = [[0, 0]];
  seen[0][0] = 1;
  while (queue.length) {
    const [r, c] = queue.shift()!;
    if (r === rows - 1 && c === cols - 1) return true;
    for (const d of [DIR_N, DIR_E, DIR_S, DIR_W]) {
      if (!(walls[r][c] & d)) continue;
      const nr = r + DR[d];
      const nc = c + DC[d];
      if (nr < 0 || nc < 0 || nr >= rows || nc >= cols) continue;
      if (seen[nr][nc]) continue;
      seen[nr][nc] = 1;
      queue.push([nr, nc]);
    }
  }
  return false;
}

/**
 * BFS from (0, 0) — return the count of cells reachable from the start.
 * For a perfect maze this should equal rows * cols (full reachability).
 */
export function reachableCount(walls: MazeWalls, rows: number, cols: number): number {
  const seen = Array.from({ length: rows }, () => new Uint8Array(cols));
  const queue: [number, number][] = [[0, 0]];
  seen[0][0] = 1;
  let count = 1;
  while (queue.length) {
    const [r, c] = queue.shift()!;
    for (const d of [DIR_N, DIR_E, DIR_S, DIR_W]) {
      if (!(walls[r][c] & d)) continue;
      const nr = r + DR[d];
      const nc = c + DC[d];
      if (nr < 0 || nc < 0 || nr >= rows || nc >= cols) continue;
      if (seen[nr][nc]) continue;
      seen[nr][nc] = 1;
      count++;
      queue.push([nr, nc]);
    }
  }
  return count;
}

/**
 * BFS shortest path from (0,0) to (rows-1, cols-1).
 * Returns the path as an array of [row, col] pairs (including start and end),
 * or null if no path exists.
 */
export function shortestPath(
  walls: MazeWalls,
  rows: number,
  cols: number,
): [number, number][] | null {
  const seen = Array.from({ length: rows }, () => new Int32Array(cols).fill(-1));
  const prev: ([number, number] | null)[][] = Array.from({ length: rows }, () =>
    Array(cols).fill(null),
  );
  const queue: [number, number][] = [[0, 0]];
  seen[0][0] = 0;
  while (queue.length) {
    const [r, c] = queue.shift()!;
    if (r === rows - 1 && c === cols - 1) {
      // reconstruct path
      const path: [number, number][] = [];
      let cur: [number, number] | null = [r, c];
      while (cur) {
        path.unshift(cur);
        cur = prev[cur[0]][cur[1]];
      }
      return path;
    }
    for (const d of [DIR_N, DIR_E, DIR_S, DIR_W]) {
      if (!(walls[r][c] & d)) continue;
      const nr = r + DR[d];
      const nc = c + DC[d];
      if (nr < 0 || nc < 0 || nr >= rows || nc >= cols) continue;
      if (seen[nr][nc] !== -1) continue;
      seen[nr][nc] = seen[r][c] + 1;
      prev[nr][nc] = [r, c];
      queue.push([nr, nc]);
    }
  }
  return null;
}
