<script setup>
/* 箭頭 Arrows — tap an arrow to send it off the board in the way it points.
   An arrow can only leave if its straight path to the edge is unobstructed.
   Puzzles are generated by reverse-placement, which guarantees they are solvable:
   each arrow is placed (in reverse removal order) only where its exit path is
   clear of the arrows already placed — so removing them in reverse always works. */

const accent = "#9aa6ff";
const CLEARED_KEY = "playground.arrows.cleared";

const DIRV = { up: [-1, 0], down: [1, 0], left: [0, -1], right: [0, 1] };
const DIFFS = [
  { key: "easy", label: "簡單", n: 5, target: 14 },
  { key: "medium", label: "中等", n: 6, target: 22 },
  { key: "hard", label: "困難", n: 7, target: 32 },
];

const difficulty = ref("medium");
const n = ref(6);
const arrows = ref([]); // { id, r, c, dir, leaving, shake, hint }
const won = ref(false);
const cleared = ref(0);
let nextId = 1;

const remaining = computed(() => arrows.value.filter((a) => !a.leaving).length);
const diffLabel = computed(() => DIFFS.find((d) => d.key === difficulty.value)?.label || "");

function shuffle(a) {
  for (let i = a.length - 1; i > 0; i--) {
    const j = (Math.random() * (i + 1)) | 0;
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function pathClearMap(occ, r, c, dir, N) {
  const [dr, dc] = DIRV[dir];
  let rr = r + dr;
  let cc = c + dc;
  while (rr >= 0 && rr < N && cc >= 0 && cc < N) {
    if (occ.has(rr * N + cc)) return false;
    rr += dr;
    cc += dc;
  }
  return true;
}

function newGame(diffKey) {
  if (diffKey) difficulty.value = diffKey;
  const d = DIFFS.find((x) => x.key === difficulty.value);
  const N = d.n;
  n.value = N;
  won.value = false;

  const occ = new Map();
  const built = [];
  let tries = 0;
  while (built.length < d.target && tries < d.target * 150) {
    tries++;
    const empties = [];
    for (let i = 0; i < N * N; i++) if (!occ.has(i)) empties.push(i);
    if (!empties.length) break;
    const idx = empties[(Math.random() * empties.length) | 0];
    const r = (idx / N) | 0;
    const c = idx % N;
    for (const dir of shuffle(["up", "down", "left", "right"])) {
      if (pathClearMap(occ, r, c, dir, N)) {
        occ.set(idx, dir);
        built.push({ id: nextId++, r, c, dir, leaving: false, shake: false, hint: false });
        break;
      }
    }
  }
  arrows.value = built;
}

function removable(a) {
  const present = new Set(
    arrows.value.filter((x) => !x.leaving).map((x) => x.r * n.value + x.c)
  );
  const [dr, dc] = DIRV[a.dir];
  let r = a.r + dr;
  let c = a.c + dc;
  while (r >= 0 && r < n.value && c >= 0 && c < n.value) {
    if (present.has(r * n.value + c)) return false;
    r += dr;
    c += dc;
  }
  return true;
}

function tap(a) {
  if (a.leaving || won.value) return;
  if (removable(a)) {
    a.leaving = true;
    setTimeout(() => {
      const i = arrows.value.findIndex((x) => x.id === a.id);
      if (i >= 0) arrows.value.splice(i, 1);
      if (!arrows.value.length) winGame();
    }, 260);
  } else {
    a.shake = true;
    setTimeout(() => (a.shake = false), 420);
  }
}

function winGame() {
  won.value = true;
  cleared.value++;
  localStorage.setItem(CLEARED_KEY, String(cleared.value));
}

function hint() {
  if (won.value) return;
  const a = arrows.value.find((x) => !x.leaving && removable(x));
  if (!a) return;
  a.hint = true;
  setTimeout(() => (a.hint = false), 700);
}

onMounted(() => {
  cleared.value = +(localStorage.getItem(CLEARED_KEY) || 0);
  newGame();
});
</script>

<template>
  <div class="game-page" :style="{ '--accent': accent }">
    <GameTopbar title="箭頭" title-en="Arrow Out">
      <template #actions>
        <button class="btn" @click="hint">提示</button>
        <button class="btn btn--accent" @click="newGame()">新遊戲</button>
      </template>
    </GameTopbar>

    <div class="stage">
      <div class="stage__main">
        <div class="hud">
          <div class="chip">
            <span class="chip__label">Level</span>
            <span class="chip__value is-accent">{{ diffLabel }}</span>
          </div>
          <div class="chip">
            <span class="chip__label">Remaining</span>
            <span class="chip__value">{{ remaining }}</span>
          </div>
          <div class="chip">
            <span class="chip__label">Cleared</span>
            <span class="chip__value">{{ cleared }}</span>
          </div>
        </div>

        <div class="board-wrap">
          <div
            class="arrows-board"
            :style="{ '--n': n }"
          >
            <button
              v-for="a in arrows"
              :key="a.id"
              class="arrow"
              :class="[`dir-${a.dir}`, { 'is-leaving': a.leaving, 'is-shake': a.shake, 'is-hint': a.hint }]"
              :style="{ gridRow: a.r + 1, gridColumn: a.c + 1 }"
              :aria-label="`箭頭 ${a.dir}`"
              @click="tap(a)"
            >
              <span class="arrow__g">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6"
                  stroke-linecap="round" stroke-linejoin="round">
                  <path d="M12 20 V5 M6 11 L12 5 L18 11" />
                </svg>
              </span>
            </button>
          </div>

          <div class="overlay" :class="{ 'is-open': won }">
            <div class="overlay__card">
              <h2 class="overlay__title">全部清空！</h2>
              <p class="overlay__sub">難度 {{ diffLabel }}　·　漂亮，所有箭頭都離開了。</p>
              <div class="overlay__actions">
                <button class="btn btn--accent" @click="newGame()">再來一局</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <aside class="panel">
        <div class="panel__group">
          <span class="panel__legend">難度</span>
          <div class="seg" role="group" aria-label="難度選擇">
            <button
              v-for="d in DIFFS"
              :key="d.key"
              :class="{ 'is-active': difficulty === d.key }"
              @click="newGame(d.key)"
            >
              {{ d.label }}
            </button>
          </div>
          <p class="hint">切換難度會開始新的一局。</p>
        </div>

        <div class="panel__group">
          <span class="panel__legend">玩法</span>
          <p class="hint">
            點一個箭頭，它會往所指的方向滑出畫面——
            但只有「前方到邊界都沒有其他箭頭擋住」的箭頭才走得出去。
            被擋住的箭頭點了會晃一下。把所有箭頭都清空即過關。
          </p>
        </div>

        <div class="panel__group">
          <span class="panel__legend">小提示</span>
          <p class="hint">先處理最外圈、前方淨空的箭頭，騰出空間後，裡層的箭頭才有路可走。卡關時可按「提示」。</p>
        </div>
      </aside>
    </div>
  </div>
</template>

<style scoped>
.arrows-board {
  position: relative;
  display: grid;
  grid-template-columns: repeat(var(--n), 1fr);
  grid-template-rows: repeat(var(--n), 1fr);
  gap: 2%;
  width: min(92vw, 60vh, 460px);
  aspect-ratio: 1;
  padding: 3%;
  border-radius: var(--r-lg);
  background-color: var(--ink-850);
  background-image: radial-gradient(circle, rgba(255, 255, 255, 0.07) 1.4px, transparent 1.6px);
  background-size: calc(100% / var(--n)) calc(100% / var(--n));
  background-position: center;
  border: 1px solid var(--line);
  box-shadow: var(--shadow-2);
  overflow: hidden;
}
.arrow {
  display: grid;
  place-items: center;
  color: var(--accent);
  border-radius: 14px;
  transition: transform 0.26s var(--ease), opacity 0.26s var(--ease);
  cursor: pointer;
}
.arrow__g {
  display: grid;
  place-items: center;
  width: 78%;
  height: 78%;
}
.arrow__g svg {
  width: 100%;
  height: 100%;
  filter: drop-shadow(0 0 6px color-mix(in oklab, var(--accent) 45%, transparent));
  transition: transform 0.15s var(--ease);
}
.arrow:hover .arrow__g svg { transform: scale(1.12); }

.dir-up .arrow__g { transform: rotate(0deg); }
.dir-right .arrow__g { transform: rotate(90deg); }
.dir-down .arrow__g { transform: rotate(180deg); }
.dir-left .arrow__g { transform: rotate(270deg); }

.arrow.is-leaving { opacity: 0; pointer-events: none; }
.arrow.is-leaving.dir-up { transform: translateY(-800%); }
.arrow.is-leaving.dir-down { transform: translateY(800%); }
.arrow.is-leaving.dir-left { transform: translateX(-800%); }
.arrow.is-leaving.dir-right { transform: translateX(800%); }

.arrow.is-hint { animation: arrowHint 0.7s var(--ease); }
@keyframes arrowHint {
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.25); }
}
.arrow.is-shake { animation: arrowShake 0.4s var(--ease); }
@keyframes arrowShake {
  0%, 100% { transform: translateX(0); }
  20% { transform: translateX(-12%); }
  40% { transform: translateX(12%); }
  60% { transform: translateX(-8%); }
  80% { transform: translateX(8%); }
}
</style>
