<script setup>
/* 四角 Shikaku — divide the whole N×M board into rectangles so that every
   rectangle frames exactly one number and its cell-count equals that number.
   Puzzles are generated by recursively partitioning the grid into rectangles
   (guillotine splits), then dropping each piece's area in as its clue — so a
   valid tiling is guaranteed to exist (and is kept around for the hint button).
   Drag to draw a rectangle; tap a drawn rectangle to remove it. */

const accent = "#34d399";
const BAD = "#ff5d6c";
const BEST_KEY = "playground.shikaku.best.";

const DIFFS = [
  { key: "easy", label: "簡單", rows: 5, cols: 5, maxArea: 6 },
  { key: "medium", label: "中等", rows: 7, cols: 7, maxArea: 8 },
  { key: "hard", label: "困難", rows: 9, cols: 9, maxArea: 9 },
];

const difficulty = ref("medium");
const rows = ref(7);
const cols = ref(7);
const clues = ref([]); // { id, r, c, value }
const rects = ref([]); // { id, r0, c0, r1, c1 }
const pending = ref(null); // { r0, c0, r1, c1 } — live during a drag
const won = ref(false);
const isRecord = ref(false);
const seconds = ref(0);
const best = ref(0);

let solution = new Map(); // clue id -> { r0, c0, r1, c1 } — a guaranteed answer
let nextId = 1;
let timerH = null;

const gridEl = ref(null);
let dragging = false;
let startCell = null;

const diffLabel = computed(() => DIFFS.find((d) => d.key === difficulty.value)?.label || "");

// ---------- geometry ----------
function areaOf(R) {
  return (R.r1 - R.r0 + 1) * (R.c1 - R.c0 + 1);
}
function cluesIn(R) {
  return clues.value.filter((k) => k.r >= R.r0 && k.r <= R.r1 && k.c >= R.c0 && k.c <= R.c1);
}
function rectState(R) {
  const cs = cluesIn(R);
  return cs.length === 1 && areaOf(R) === cs[0].value ? "valid" : "invalid";
}
function intersects(A, B) {
  return !(A.c1 < B.c0 || A.c0 > B.c1 || A.r1 < B.r0 || A.r0 > B.r1);
}
function contains(R, r, c) {
  return r >= R.r0 && r <= R.r1 && c >= R.c0 && c <= R.c1;
}
function boxStyle(R) {
  return {
    left: (R.c0 / cols.value) * 100 + "%",
    top: (R.r0 / rows.value) * 100 + "%",
    width: ((R.c1 - R.c0 + 1) / cols.value) * 100 + "%",
    height: ((R.r1 - R.r0 + 1) / rows.value) * 100 + "%",
  };
}
function clueStyle(k) {
  return {
    left: ((k.c + 0.5) / cols.value) * 100 + "%",
    top: ((k.r + 0.5) / rows.value) * 100 + "%",
  };
}

const rectViews = computed(() =>
  rects.value.map((R) => ({ id: R.id, state: rectState(R), style: boxStyle(R) }))
);
const pendingView = computed(() =>
  pending.value ? { state: rectState(pending.value), style: boxStyle(pending.value) } : null
);
const solvedCount = computed(() => rects.value.filter((R) => rectState(R) === "valid").length);

// ---------- generation ----------
function genShikaku(R, C, maxArea) {
  const leaves = [];
  const rnd = (n) => (Math.random() * n) | 0;
  // bigger pieces are likelier to be split again → a varied mix of rectangles
  function pStop(area) {
    if (area > maxArea) return 0;
    if (area <= 1) return 1;
    return Math.min(0.92, Math.max(0.06, 0.95 - area / maxArea));
  }
  function split(r0, c0, r1, c1) {
    const h = r1 - r0 + 1;
    const w = c1 - c0 + 1;
    const area = h * w;
    if ((h === 1 && w === 1) || (area <= maxArea && Math.random() < pStop(area))) {
      leaves.push({ r0, c0, r1, c1 });
      return;
    }
    let horiz;
    if (h === 1) horiz = false;
    else if (w === 1) horiz = true;
    else if (h > w) horiz = Math.random() < 0.72; // prefer cutting the longer side
    else if (w > h) horiz = Math.random() < 0.28;
    else horiz = Math.random() < 0.5;
    if (horiz) {
      const cut = r0 + 1 + rnd(h - 1);
      split(r0, c0, cut - 1, c1);
      split(cut, c0, r1, c1);
    } else {
      const cut = c0 + 1 + rnd(w - 1);
      split(r0, c0, r1, cut - 1);
      split(r0, cut, r1, c1);
    }
  }
  split(0, 0, R - 1, C - 1);

  const cl = [];
  const sol = new Map();
  let id = 1;
  for (const lf of leaves) {
    const cid = id++;
    const cr = lf.r0 + rnd(lf.r1 - lf.r0 + 1);
    const cc = lf.c0 + rnd(lf.c1 - lf.c0 + 1);
    cl.push({ id: cid, r: cr, c: cc, value: areaOf(lf) });
    sol.set(cid, lf);
  }
  return { clues: cl, solution: sol };
}

function newGame(diffKey) {
  if (diffKey) difficulty.value = diffKey;
  const d = DIFFS.find((x) => x.key === difficulty.value);
  rows.value = d.rows;
  cols.value = d.cols;
  const g = genShikaku(d.rows, d.cols, d.maxArea);
  clues.value = g.clues;
  solution = g.solution;
  rects.value = [];
  pending.value = null;
  dragging = false;
  won.value = false;
  isRecord.value = false;
  best.value = Number(localStorage.getItem(BEST_KEY + difficulty.value) || 0);
  seconds.value = 0;
  startTimer();
}

// ---------- pointer input (mouse + touch, one path) ----------
function cellAt(e) {
  const el = gridEl.value;
  if (!el) return { r: 0, c: 0 };
  const box = el.getBoundingClientRect();
  const c = Math.min(cols.value - 1, Math.max(0, Math.floor((e.clientX - box.left) / (box.width / cols.value))));
  const r = Math.min(rows.value - 1, Math.max(0, Math.floor((e.clientY - box.top) / (box.height / rows.value))));
  return { r, c };
}
function onDown(e) {
  if (won.value) return;
  if (e.pointerType === "mouse" && e.button !== 0) return;
  e.preventDefault();
  gridEl.value?.setPointerCapture?.(e.pointerId);
  const cell = cellAt(e);
  dragging = true;
  startCell = cell;
  pending.value = { r0: cell.r, c0: cell.c, r1: cell.r, c1: cell.c };
}
function onMove(e) {
  if (!dragging) return;
  const cell = cellAt(e);
  const s = startCell;
  pending.value = {
    r0: Math.min(s.r, cell.r),
    c0: Math.min(s.c, cell.c),
    r1: Math.max(s.r, cell.r),
    c1: Math.max(s.c, cell.c),
  };
}
function onUp() {
  if (!dragging) return;
  dragging = false;
  const p = pending.value;
  pending.value = null;
  if (!p) return;
  // a tap (no drag) on an existing rectangle removes it
  if (p.r0 === p.r1 && p.c0 === p.c1) {
    const hit = rects.value.find((R) => contains(R, p.r0, p.c0));
    if (hit) {
      rects.value = rects.value.filter((R) => R.id !== hit.id);
      return;
    }
  }
  // otherwise draw the box, replacing anything it overlaps
  rects.value = rects.value.filter((R) => !intersects(R, p));
  rects.value.push({ id: nextId++, r0: p.r0, c0: p.c0, r1: p.r1, c1: p.c1 });
  checkWin();
}
function onCancel() {
  dragging = false;
  pending.value = null;
}

// ---------- actions ----------
function clearAll() {
  if (won.value) return;
  rects.value = [];
}
function hint() {
  if (won.value) return;
  const unsolved = clues.value.filter((k) => {
    const s = solution.get(k.id);
    return !rects.value.some(
      (R) => R.r0 === s.r0 && R.c0 === s.c0 && R.r1 === s.r1 && R.c1 === s.c1
    );
  });
  if (!unsolved.length) return;
  const s = solution.get(unsolved[(Math.random() * unsolved.length) | 0].id);
  rects.value = rects.value.filter((R) => !intersects(R, s));
  rects.value.push({ id: nextId++, r0: s.r0, c0: s.c0, r1: s.r1, c1: s.c1 });
  checkWin();
}

// ---------- win / timer ----------
function checkWin() {
  const total = rows.value * cols.value;
  let covered = 0;
  for (const R of rects.value) {
    if (rectState(R) !== "valid") return;
    covered += areaOf(R);
  }
  if (covered === total && rects.value.length === clues.value.length) win();
}
function win() {
  if (won.value) return;
  won.value = true;
  stopTimer();
  const key = BEST_KEY + difficulty.value;
  const prev = Number(localStorage.getItem(key) || 0);
  if (!prev || seconds.value < prev) {
    localStorage.setItem(key, String(seconds.value));
    best.value = seconds.value;
    isRecord.value = true;
  }
}
function startTimer() {
  stopTimer();
  timerH = setInterval(() => seconds.value++, 1000);
}
function stopTimer() {
  if (timerH) {
    clearInterval(timerH);
    timerH = null;
  }
}
function fmt(s) {
  return String(Math.floor(s / 60)).padStart(2, "0") + ":" + String(s % 60).padStart(2, "0");
}
const timeStr = computed(() => fmt(seconds.value));
const bestStr = computed(() => (best.value ? fmt(best.value) : "—"));

onMounted(() => newGame());
onBeforeUnmount(() => stopTimer());
</script>

<template>
  <div class="game-page" :style="{ '--accent': accent, '--bad': BAD }">
    <GameTopbar title="四角" title-en="Shikaku">
      <template #actions>
        <button class="btn" @click="hint">提示</button>
        <button class="btn btn--accent" @click="newGame()">新遊戲</button>
      </template>
    </GameTopbar>

    <div class="stage">
      <div class="stage__main">
        <div class="hud">
          <div class="chip">
            <span class="chip__label">Time</span>
            <span class="chip__value is-accent">{{ timeStr }}</span>
          </div>
          <div class="chip">
            <span class="chip__label">Clues</span>
            <span class="chip__value">{{ solvedCount }} / {{ clues.length }}</span>
          </div>
          <div class="chip">
            <span class="chip__label">Best</span>
            <span class="chip__value">{{ bestStr }}</span>
          </div>
        </div>

        <div class="board-wrap">
          <div class="sk-board">
            <div
              ref="gridEl"
              class="sk-grid"
              :class="{ 'is-won': won }"
              :style="{ '--rows': rows, '--cols': cols }"
              @pointerdown="onDown"
              @pointermove="onMove"
              @pointerup="onUp"
              @pointercancel="onCancel"
              @contextmenu.prevent
            >
              <div v-for="i in rows * cols" :key="i" class="sk-cell"><span /></div>

              <div
                v-for="R in rectViews"
                :key="R.id"
                class="sk-rect"
                :class="'is-' + R.state"
                :style="R.style"
              >
                <span class="sk-rect__fill" />
              </div>

              <div
                v-if="pendingView"
                class="sk-rect sk-rect--pending"
                :class="'is-' + pendingView.state"
                :style="pendingView.style"
              >
                <span class="sk-rect__fill" />
              </div>

              <div v-for="k in clues" :key="'c' + k.id" class="sk-clue" :style="clueStyle(k)">
                {{ k.value }}
              </div>
            </div>
          </div>

          <div class="overlay" :class="{ 'is-open': won }">
            <div class="overlay__card">
              <h2 class="overlay__title">{{ isRecord ? "新紀錄！" : "完成！" }}</h2>
              <p class="overlay__sub">
                難度 {{ diffLabel }}　·　用時 {{ timeStr }}{{ isRecord ? "（最佳）" : ` · 最佳 ${bestStr}` }}
              </p>
              <div class="overlay__actions">
                <button class="btn btn--accent" @click="newGame()">再來一局</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <aside class="panel">
        <div class="panel__group">
          <span class="panel__legend">難度</span>
          <div class="seg" role="group" aria-label="難度選擇">
            <button
              v-for="d in DIFFS"
              :key="d.key"
              :class="{ 'is-active': difficulty === d.key }"
              @click="newGame(d.key)"
            >
              {{ d.label }}
            </button>
          </div>
          <p class="hint">切換難度會開始新的一局（目前 {{ rows }}×{{ cols }} 格）。</p>
        </div>

        <div class="panel__group">
          <span class="panel__legend">玩法</span>
          <p class="hint">
            把整個棋盤切成數個<strong>長方形</strong>：每個長方形必須剛好框住<strong>一個數字</strong>，
            而且框內的<strong>格子數要等於那個數字</strong>。所有格子都要被填滿、且彼此不重疊。
          </p>
        </div>

        <div class="panel__group">
          <span class="panel__legend">操作</span>
          <p class="hint">
            在棋盤上<strong>拖曳</strong>畫出長方形；<strong>點一下</strong>已畫好的方框即可移除。
            正確的框會變<span class="ink-accent">綠色</span>，不正確則顯示<span class="ink-bad">紅色</span>。
          </p>
          <button class="btn btn--ghost panel__btn" @click="clearAll">清空全部</button>
        </div>

        <div class="panel__group">
          <span class="panel__legend">小提示</span>
          <p class="hint">
            先從只有一種畫法的數字下手——靠牆角、或數字特別大／特別小的格子，可走的選擇通常很有限。卡關時可按「提示」自動補上一塊。
          </p>
        </div>
      </aside>
    </div>
  </div>
</template>

<style scoped>
.sk-board {
  padding: clamp(8px, 2.4vw, 16px);
  border-radius: var(--r-lg);
  background: var(--ink-700);
  border: 1px solid var(--line);
  box-shadow: var(--shadow-2);
}
.sk-grid {
  --rad: clamp(6px, 2.2cqw, 13px);
  position: relative;
  width: min(92vw, 58vh, 460px);
  aspect-ratio: var(--cols) / var(--rows);
  display: grid;
  grid-template-columns: repeat(var(--cols), 1fr);
  grid-template-rows: repeat(var(--rows), 1fr);
  container-type: inline-size;
  touch-action: none;
  user-select: none;
  -webkit-user-select: none;
  -webkit-touch-callout: none;
}

/* cells (gap is created by each item's padding, so 1 cell = exactly 1/cols)  */
.sk-cell {
  padding: 1.5cqw;
}
.sk-cell > span {
  display: block;
  width: 100%;
  height: 100%;
  border-radius: var(--rad);
  background: var(--ink-850);
}

/* player rectangles — positioned by exact % since the grid has no gap */
.sk-rect {
  position: absolute;
  padding: 1.5cqw;
  pointer-events: none;
  z-index: 1;
}
.sk-rect__fill {
  display: block;
  width: 100%;
  height: 100%;
  box-sizing: border-box;
  border-radius: var(--rad);
  transition: background 0.16s var(--ease), border-color 0.16s var(--ease);
}
.sk-rect.is-valid .sk-rect__fill {
  background: color-mix(in oklab, var(--accent) 30%, transparent);
  border: 2px solid color-mix(in oklab, var(--accent) 78%, transparent);
  box-shadow: inset 0 0 24px color-mix(in oklab, var(--accent) 18%, transparent);
}
.sk-rect.is-invalid .sk-rect__fill {
  background: color-mix(in oklab, var(--bad) 20%, transparent);
  border: 2px solid color-mix(in oklab, var(--bad) 66%, transparent);
}
.sk-rect--pending {
  z-index: 2;
}
.sk-rect--pending .sk-rect__fill {
  border-style: dashed;
  border-width: 2.5px;
}

.sk-clue {
  position: absolute;
  transform: translate(-50%, -50%);
  pointer-events: none;
  z-index: 3;
  font-family: var(--font-display);
  font-weight: 800;
  font-size: calc(48cqw / var(--cols));
  color: var(--text);
  text-shadow: 0 1px 3px rgba(0, 0, 0, 0.7);
}

.sk-grid.is-won .sk-rect__fill {
  animation: skWin 0.5s var(--ease);
}
@keyframes skWin {
  0% { transform: scale(1); }
  45% { transform: scale(0.94); }
  100% { transform: scale(1); }
}

.panel__btn {
  width: 100%;
}
.ink-accent {
  color: var(--accent);
  font-weight: 700;
}
.ink-bad {
  color: var(--bad);
  font-weight: 700;
}
</style>
